import matplotlib.pyplot as plt
import numpy as np

if __name__ == "__main__":
    objective_gd_100 = np.load("data/objective_gd_100.npy")
    objective_new_100 = np.load("data/objective_new_100.npy")
    objective_sgd_100 = np.load("data/objective_sgd_100.npy")
    time_gd_100 = np.load("data/time_gd_100.npy")
    time_new_100 = np.load("data/time_new_100.npy")
    time_sgd_100 = np.load("data/time_sgd_100.npy")

    objective_gd_1000 = np.load("data/objective_gd_1000.npy")
    objective_new_1000 = np.load("data/objective_new_1000.npy")
    objective_sgd_1000 = np.load("data/objective_sgd_1000.npy")
    time_gd_1000 = np.load("data/time_gd_1000.npy")
    time_new_1000 = np.load("data/time_new_1000.npy")
    time_sgd_1000 = np.load("data/time_sgd_1000.npy")

    plt.plot(objective_gd_100)
    plt.plot(objective_new_100)
    plt.plot(objective_sgd_100)
    plt.ylabel("Objective")
    plt.xlabel("Iterations")
    plt.legend(["Gradient Descent", "Newton", "SGD"])
    plt.title("M = 100")
    plt.savefig("norm_m_100.png", dpi=600)
    plt.show()

    plt.plot(objective_gd_1000)
    plt.plot(objective_new_1000)
    plt.plot(objective_sgd_1000)
    plt.ylabel("Objective")
    plt.xlabel("Iterations")
    plt.ylim(bottom=690, top=700)
    plt.legend(["Gradient Descent", "Newton", "SGD"])
    plt.title("M = 1000")
    plt.savefig("norm_m_1000.png", dpi=600)
    plt.show()

    plt.plot(time_gd_100)
    plt.plot(time_new_100)
    plt.plot(time_sgd_100)
    plt.ylabel("Time")
    plt.xlabel("Iterations")
    plt.legend(["Gradient Descent", "Newton", "SGD"])
    plt.title("Time when M = 100")
    plt.savefig("time_m_100.png", dpi=600)
    plt.show()

    plt.plot(time_gd_1000)
    plt.plot(time_new_1000)
    plt.plot(time_sgd_1000)
    plt.ylabel("Time")
    plt.xlabel("Iterations")
    plt.legend(["Gradient Descent", "Newton", "SGD"])
    plt.title("Time when M = 1000")
    plt.savefig("time_m_1000.png", dpi=600)
    plt.show()